- dreamteamClient/.gitignore
- dreamteamClient/README.md
- dreamteamClient/package-lock.json
- dreamteamClient/package.json
- dreamteamClient/public/index.html
- dreamteamClient/src/index.js
- dreamteamClient/src/reportWebVitals.js
Had to change the "client" folder to "dreamteamClient" because of the react naming convention and the app build config.
> adding files and react library to dreamteamClient

- dreamteamClient/src/App.js
- dreamteamClient/src/Components/Key/Key.js
- dreamteamClient/src/Components/Keyboard/Keyboard.js
- dreamteamClient/src/index.js
- package-lock.json
watched Sarah D. put this in and it is all good
> adding Key and Keyboard Components

- dreamteamClient/src/App.js
- dreamteamClient/src/Components/Keyboard/Keyboard.js
- dreamteamClient/src/index.js
- dreamteamClient/src/utils/KeysObj.js
"key rendering on local but button component not rendering"
> created keyobject js mapped to keyboard\

- dreamteamClient/src/Components/Key/Key.js
- dreamteamClient/src/utils/KeysObj.js
> identifying each piano key and keyvalue pairs in object

- client/public/index.html
- client/src/Components/Button/Button.css
- client/src/Components/Button/Button.js
Button is all set. It will be able to take in any finctionality and "value" can be set to whatever the button text will be ie. "Sign Up" "Log-In", etc.
> Button component all set

- client/src/Components/Keyboard/Keyboard.js
- client/src/Components/Login/Login.js
- client/src/Components/Slider/Slider.js
- client/src/index.js
> adding Material ui Slider

- client/src/components/BlackRow/BlackRow.css
- client/src/components/Presets/Presets.css
- client/src/components/Presets/SavePreset.js
- client/src/components/WhiteRow/WhiteRow.css
- client/src/pages/SynthPage/SynthPage.css
- client/src/pages/SynthPage/SynthPage.js
removed bulets and fixed alignment issues.
> Preset button styles

- client/src/components/Keyboard/Keyboard.js
- client/src/components/Slider/Slider.css
- client/src/components/Slider/Slider.js
- client/src/components/SliderContainer/SliderContainer.css
- client/src/components/SliderContainer/SliderContainer.js
- client/src/pages/SynthPage/SynthPage.js
> Sliderstyle1

- client/src/components/Keyboard/Keyboard.js
- client/src/components/WhiteKey/WhiteKey.js
- client/src/utils/oscillator.js
Reverts ColinMudie/Dream-Team#92
> Revert "added keyboard events to trigger the synth"

- client/src/components/Keyboard/Keyboard.js
- client/src/components/WhiteKey/WhiteKey.js
- client/src/utils/oscillator.js
Reverts ColinMudie/Dream-Team#93
> Revert "Revert "added keyboard events to trigger the synth""

- client/src/components/Keyboard/Keyboard.css
- client/src/components/Presets/Presets.css
- client/src/components/Presets/Presets.js
- client/src/components/SaveButton/SaveButton.css
- client/src/components/SaveButton/SaveButton.js
- client/src/pages/SynthPage/SynthPage.css
Added load and save buttons. Fixed overflow issue.
> Load save button

- client/src/components/Login/Login.css
- client/src/components/Login/Login.js
- client/src/components/Signup/Signup.css
- client/src/components/Signup/Signup.js
made the sign-in page and sign-up pages to match our design board. Used Materail ui to make it device responsive.
> Signinlogin

- client/public/index.html
- client/src/components/BlackKey/BlackKey.js
- client/src/components/BlackRow/BlackRow.css
- client/src/components/WhiteKey/WhiteKey.js
- client/src/components/WhiteRow/WhiteRow.css
- client/src/utils/blackObj.js
- client/src/utils/blackObj2.js
Added proper sharp and flat symbols and repositioned notes within keys.
> repositioned notes

- client/src/components/Keyboard/Keyboard.js
- client/src/utils/oscillator.js
still need to have the oscillator.js continue the sustain without retriggering to have a longer note.
> fixed distortion problem & fixed visual css sustain on keyClick

- client/public/index.html
- client/src/components/Login/Login.css
- client/src/components/Login/Login.js
new font added, text enlarged, added space, and brought down login/signup form toward middle of screen.
> Login/Sign Up stlyes tweaked

- client/src/components/Login/Login.css
- client/src/components/Login/Login.js
Added class to avoid styling conflicts with other components.
> changed class affecting radio buttons

- client/src/components/CheckBoxWave/CheckBoxWave.css
- client/src/components/CheckBoxWave/CheckBoxWave.js
- client/src/pages/SynthPage/SynthPage.js
> centered radio boxes

- README.md
- client/src/components/ButtonLogOut/ButtonLogOut.css
- client/src/components/CheckBoxWave/CheckBoxWave.css
- client/src/components/Presets/Presets.css
- client/src/components/SaveButton/SaveButton.css
- client/src/components/Signup/Signup.js
- client/src/components/Slider/Slider.css
Added Poppins font and improved spacing and alignment.
> Final styling2

- client/src/components/ButtonLogOut/ButtonLogOut.css
- client/src/components/ButtonLogOut/ButtonLogOut.js
- client/src/components/CheckBoxWave/CheckBoxWave.css
- client/src/components/CheckBoxWave/CheckBoxWave.js
- client/src/components/Header/Header.css
- client/src/components/Header/Header.js
- client/src/components/Keyboard/Keyboard 2.css
- client/src/components/Login/Login.css
- client/src/components/Login/Login.js
- client/src/components/Presets/Presets.css
- client/src/components/Slider/Slider.css
- client/src/components/SliderContainer/SliderContainer.css
- client/src/pages/SynthPage/SynthPage.css
- client/src/pages/SynthPage/SynthPage.js
Added media queries for mobile sizing. Made minor adjustments to some components to make up for spacing issues.
> Media query mobile

- client/src/pages/SynthPage/SynthPage.css
Hopefully fixed the background color issue and it should fill the entire screen now.
> fixing background color

- client/src/pages/SynthPage/SynthPage.css
Changed media query to allow background color when in portrait orientation on mobile.
> hopefully fixing background issue
